Resources:
  RequestAdditionDlqSqsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.variables.request-addition-dlq-sqs-queue-name}
      FifoQueue: true
      KmsMasterKeyId: ${self:custom.variables.kms-custom-master-key}

  RequestAdditionSqsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.variables.request-addition-sqs-queue-name}
      FifoQueue: true
      KmsMasterKeyId: ${self:custom.variables.kms-custom-master-key}
      RedrivePolicy:
        deadLetterTargetArn: { 'Fn::GetAtt': ['RequestAdditionDlqSqsQueue', 'Arn'] }
        maxReceiveCount: 5




  RequestAdditionSqsQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - Ref: RequestAdditionSqsQueue
        - Ref: RequestAdditionSnsTopicSubscriptionDLQ
      PolicyDocument:
        Statement:
          Effect: Allow
          Principal: '*'
          Action: sqs:SendMessage
          Resource: '*'
          Condition:
            ArnEquals:
              aws:SourceArn: ${self:custom.variables.request-sns-topic-arn}
