Resources:
  ReplyAdditionSnsTopic:
    Type: AWS::SNS::Topic
    Properties:
      ContentBasedDeduplication: false
      FifoTopic: true
      KmsMasterKeyId: ${self:custom.variables.kms-custom-master-key}
      TopicName: ${self:custom.variables.reply-addition-sns-topic-name}
