Resources:
  ReplyAdditionDlqSqsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.variables.reply-addition-dlq-sqs-queue-name}
      FifoQueue: true
      KmsMasterKeyId: ${self:custom.variables.kms-custom-master-key}

  ReplyAdditionSqsQueue:
    Type: AWS::SQS::Queue
    Properties:
      QueueName: ${self:custom.variables.reply-addition-sqs-queue-name}
      FifoQueue: true
      KmsMasterKeyId: ${self:custom.variables.kms-custom-master-key}
      RedrivePolicy:
        deadLetterTargetArn: { 'Fn::GetAtt': ['ReplyAdditionDlqSqsQueue', 'Arn'] }
        maxReceiveCount: 5




  ReplyAdditionSqsQueuePolicy:
    Type: AWS::SQS::QueuePolicy
    Properties:
      Queues:
        - Ref: ReplyAdditionSqsQueue
        - Ref: ReplyAdditionSnsTopicSubscriptionDLQ
      PolicyDocument:
        Statement:
          Effect: Allow
          Principal: '*'
          Action: sqs:SendMessage
          Resource: '*'
          Condition:
            ArnEquals:
              aws:SourceArn: ${self:custom.variables.reply-addition-sns-topic-arn}
